# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "LTA38753https://lta38753.snowflakecomputing.com"
user = "AMEHROTRA"
password = "Rajeev@251"
role = "DATA_ENGINEERING"
warehouse = "DE_WH"
database = "AMEHROTRA"
schema = "SNOWPARK_DEMO"
